import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ProjectProvider } from "./context/ProjectContext";
import Sidebar from "./components/sidebar";
import UserMenu from "./components/UserMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProjectProvider>
          <div className="app-wrapper flex h-[100dvh] w-[100%]">
            <Sidebar />
            <main className="table wrapper py-6 px-10 grow">
              {/* User menu in top right */}
              <div className="flex justify-end mb-4">
                <UserMenu />
              </div>
              {children}
            </main>
          </div>
        </ProjectProvider>
      </body>
    </html>
  );
}
