import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/sidebar";
import { ProjectProvider } from "./context/ProjectContext";
import { getServerSession } from "next-auth";
import SessionProvider from "../components/SessionProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <ProjectProvider>
            <div className="app-wrapper flex h-[100dvh] w-[100%]">
              <Sidebar></Sidebar>
              <main className="table wrapper py-6 px-10 grow">{children}</main>
            </div>
          </ProjectProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
